### ISSUE TITLE
.elapsed sometimes is negative

### ISSUE THREAD

**Issue by iacopo-papalini** [quantumsheep/node-icmp#2]
Only the nanosecond part of the hrtimer is considered when computing the elapsed time.
As stated in the [official documentation](https://nodejs.org/api/process.html#process_process_hrtime_time) 

> `nanoseconds` is the remaining part of the real time that can't be represented in second precision.

 If the ping starts nearby the end of a second, and ends soon after the beginning of the following second, the difference is negative. 

### Proposed solution:

Replace lines 71-72 with the following:
>                const NS_PER_SEC = 1e9;
>                this.diff = process.hrtime(this.start);
>                this.elapsed = (this.diff[0]  + this.diff[1] / NS_PER_SEC) * 1000;

**Comment by quantumsheep** [comment]
Thanks! I also removed `ICMP.end` property, it was useless 😄
