### ISSUE TITLE
Replying to icmp.send?

### ISSUE THREAD

**Issue by Stwissel** [quantumsheep/node-icmp#3]
Question:

is there a sample code for a ICMP reply in NodeJS to a send request from your library?

**Comment by quantumsheep** [comment]
You mean listening to ICMP requests?

**Comment by Stwissel** [comment]
Yes. Sorry for not being clear.

Background: I was wondering if ICMP would be the right way to "auto-configure" a distributed app. Like a client send a request to the local IP addresses (eventually via the broadcast address (?) and the server application replies, so the client finds the local server to talk to.
The application relies on a server in the same subnet

**Comment by quantumsheep** [comment]
For now I added `.listen()` method for listening to incoming requests but it seems like we can't make a custom answer to ICMP requests. I'll make researches, I keep you up to date :)

Commit https://github.com/quantumsheep/node-icmp/commit/162ae6f687c813ed50c0147b129c8e74f3cbd14c
