### ISSUE TITLE
Using Typescript, ICMP is undefined

### ISSUE THREAD

**Issue by disolva** [quantumsheep/node-icmp#9]
Hi,
just wondering if this is a TS an issue, as I have not tried it differently. 

Thanks

**Comment by quantumsheep** [comment]
How do you import the package?

In any case a conversion to TypeScript is needed - I'll work on a TypeScript version.

**Comment by disolva** [comment]
`import ICMP from 'icmp'`

And I wanted to add that this is a runtime exception.

Actually I do not know why, but IntelliSense has not detected this dependency which occured very unusual. But this is my very first full TS project, I'm not fully aware of all the consequences.

Have you considered contribution? Give me a hint, maybe I can help with some stuff

**Comment by quantumsheep** [comment]
Have you tried doing `import * as ICMP from 'icmp'`?

I'm open to contributions, if you want you can try to convert the project into TS.

**Comment by disolva** [comment]
Thats perfect, thanks. Just forgot to try that one.

Lets see what the schedule says, but I'm actually interested as this is not a huge enterprise project for this excercise.
